version: "3.7"

services:
  server:
    image: drone/drone:latest
    container_name: drone_server
    restart: always
    env_file: .env
    networks:
      - common_link
      - drone_link
  runner_docker:
    image: drone/drone-runner-docker:latest
    container_name: drone_runner_docker
    restart: always
    env_file: .env
    networks:
      - drone_link
    ports:
      - "3000:3000"
    depends_on:
      - server
  runner_ssh:
    image: drone/drone-runner-ssh:latest
    container_name: drone_runner_ssh
    restart: always
    env_file: .env
    networks:
      - drone_link
    ports:
      - "3000:3000"
    depends_on:
      - server

networks:
  common_link:
    external: true
  drone_link:
